Repository prgrms-web-devcourse-final-project/WEB2_3_Wooamo_BE, pull requests merged in 2025-02, with the labels that each got.

#4 [#1] 친구 요청 기능
  src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
  src/main/java/com/api/stuv/domain/friend/dto/FriendFollowResponse.java
  src/main/java/com/api/stuv/domain/friend/entity/Friend.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepository.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepository.java
Labels: ✨ Feature

#7 [#5] 친구 수락 기능 구현
  src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
  src/main/java/com/api/stuv/domain/friend/entity/Friend.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
  src/test/java/com/api/stuv/domain/friend/service/AcceptFriendRequestTest.java
Labels: ✨ Feature

#10 [#9] 에러 및 응답 구조 변경
  src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
  src/main/java/com/api/stuv/global/exception/AccessDeniedException.java
  src/main/java/com/api/stuv/global/exception/BadRequestException.java
  src/main/java/com/api/stuv/global/exception/DuplicateException.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
  src/main/java/com/api/stuv/global/exception/GlobalExceptionHandler.java
  src/main/java/com/api/stuv/global/exception/NotFoundException.java
Labels: 🔨 Refactor

#12 [#2] 회원가입 기능
  build.gradle
  src/main/java/com/api/stuv/domain/user/controller/userController.java
  src/main/java/com/api/stuv/domain/user/dto/request/EmailCertificationRequest.java
  src/main/java/com/api/stuv/domain/user/dto/request/UserRequest.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepository.java
  src/main/java/com/api/stuv/domain/user/response/GenerateNicknameResponse.java
  src/main/java/com/api/stuv/domain/user/service/userService.java
  src/main/java/com/api/stuv/global/config/WebClientConfig.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
  src/main/java/com/api/stuv/global/service/RedisService.java
  src/main/java/com/api/stuv/global/util/email/RandomCode.java
  src/main/java/com/api/stuv/global/util/email/provider/EmailProvider.java
Labels: ✨ Feature

#15 [#6] 게시판 목록 조회
  src/main/java/com/api/stuv/domain/board/controller/BoardController.java
  src/main/java/com/api/stuv/domain/board/dto/BoardResponse.java
  src/main/java/com/api/stuv/domain/board/entity/Board.java
  src/main/java/com/api/stuv/domain/board/entity/BoardType.java
  src/main/java/com/api/stuv/domain/board/entity/Comment.java
  src/main/java/com/api/stuv/domain/board/repository/BoardRepository.java
  src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepository.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
  src/main/java/com/api/stuv/global/exception/GlobalExceptionHandler.java
  src/main/java/com/api/stuv/global/response/PageResponse.java
Labels: ✨ Feature

#13 [#3] 커스튬 등록 기능 구현
  src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
  src/main/java/com/api/stuv/domain/admin/dto/CreateCostumeRequest.java
  src/main/java/com/api/stuv/domain/admin/exception/InvalidPointFormat.java
  src/main/java/com/api/stuv/domain/admin/service/AdminService.java
  src/main/java/com/api/stuv/domain/image/entity/ImageFile.java
  src/main/java/com/api/stuv/domain/image/entity/ImageType.java
  src/main/java/com/api/stuv/domain/image/exception/ImageFileNotFound.java
  src/main/java/com/api/stuv/domain/image/exception/InvalidImageFileFormat.java
  src/main/java/com/api/stuv/domain/image/service/ImageService.java
  src/main/java/com/api/stuv/domain/image/service/S3ImageService.java
  src/main/java/com/api/stuv/domain/image/util/FileUtils.java
  src/main/java/com/api/stuv/domain/shop/entity/Costume.java
Labels: ✨ Feature

#17 [#16] 친구 요청 목록 조회
  src/main/java/com/api/stuv/domain/board/controller/BoardController.java
  src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
  src/main/java/com/api/stuv/domain/friend/dto/FriendFollowListResponse.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepository.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryCustom.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
  src/main/java/com/api/stuv/global/response/PageResponse.java
  src/main/java/com/api/stuv/global/util/email/common/TemplateUtils.java
Labels: ✨ Feature

#22 [#18] 코멘트 리스트 조회
  src/main/java/com/api/stuv/domain/board/controller/BoardController.java
  src/main/java/com/api/stuv/domain/board/dto/CommentResponse.java
  src/main/java/com/api/stuv/domain/board/entity/Board.java
  src/main/java/com/api/stuv/domain/board/entity/Comment.java
  src/main/java/com/api/stuv/domain/board/repository/CommentRepository.java
  src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryCustom.java
  src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryImpl.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
  src/main/java/com/api/stuv/domain/friend/entity/Friend.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
  src/main/java/com/api/stuv/global/exception/NotFoundException.java
  src/main/java/com/api/stuv/global/response/PageResponse.java
  src/test/java/com/api/stuv/domain/friend/service/AcceptFriendRequestTest.java
Labels: ✨ Feature

#25 [#23] 코멘트작성
  src/main/java/com/api/stuv/domain/board/controller/BoardController.java
  src/main/java/com/api/stuv/domain/board/entity/Comment.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
Labels: ✨ Feature

#24 [#14] 로그인, 로그아웃 기능
  src/main/java/com/api/stuv/domain/auth/controller/ReissueController.java
  src/main/java/com/api/stuv/domain/auth/dto/CustomUserDetails.java
  src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
  src/main/java/com/api/stuv/domain/auth/jwt/JWTFilter.java
  src/main/java/com/api/stuv/domain/auth/jwt/JWTUtil.java
  src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
  src/main/java/com/api/stuv/domain/auth/service/CustomUserDetailsService.java
  src/main/java/com/api/stuv/domain/auth/service/ReissueService.java
  src/main/java/com/api/stuv/domain/auth/util/TokenUtil.java
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/dto/request/LoginRequest.java
  src/main/java/com/api/stuv/domain/user/entity/RoleType.java
  src/main/java/com/api/stuv/domain/user/entity/User.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepository.java
  src/main/java/com/api/stuv/domain/user/service/userService.java
  src/main/java/com/api/stuv/global/config/SecurityConfig.java
  src/main/java/com/api/stuv/global/service/RedisService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#35 [#33] Redis 직렬화/역직렬화 오류 핫픽스
  src/main/java/com/api/stuv/global/service/RedisService.java
  src/test/java/com/api/stuv/global/service/RedisServiceTest.java
Labels: 🐞 BugFix

#34 [#32] 친구 목록
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
  src/main/java/com/api/stuv/domain/friend/dto/FriendResponse.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryCustom.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
Labels: ✨ Feature

#29 [#19] 코스튬 목록 조회 구현
  src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
  src/main/java/com/api/stuv/domain/image/service/S3ImageService.java
  src/main/java/com/api/stuv/domain/shop/controller/CostumeController.java
  src/main/java/com/api/stuv/domain/shop/dto/CostumeResponse.java
  src/main/java/com/api/stuv/domain/shop/entity/Costume.java
  src/main/java/com/api/stuv/domain/shop/repository/CostumeRepository.java
  src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryCustom.java
  src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryImpl.java
  src/main/java/com/api/stuv/domain/shop/service/CostumeService.java
Labels: ✨ Feature

#36 [#30] 코스튬 수정 기능 구현
  src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
  src/main/java/com/api/stuv/domain/admin/dto/CostumeRequest.java
  src/main/java/com/api/stuv/domain/admin/exception/CostumeNotFound.java
  src/main/java/com/api/stuv/domain/admin/service/AdminService.java
  src/main/java/com/api/stuv/domain/shop/entity/Costume.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
Labels: ✨ Feature

#39 [#37] 코스튬 삭제 기능 구현
  src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
  src/main/java/com/api/stuv/domain/admin/service/AdminService.java
  src/main/java/com/api/stuv/domain/image/exception/ImageFileNameNotFound.java
  src/main/java/com/api/stuv/domain/image/service/S3ImageService.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
Labels: ✨ Feature

#40 [#8] 팟 목록 조회 - 시작 예정, 참여중
  src/main/java/com/api/stuv/domain/admin/.gitkeep
  src/main/java/com/api/stuv/domain/party/controller/PartyController.java
  src/main/java/com/api/stuv/domain/party/dto/response/PartyGroupResponse.java
  src/main/java/com/api/stuv/domain/party/entity/PartyGroup.java
  src/main/java/com/api/stuv/domain/party/entity/PartyStatus.java
  src/main/java/com/api/stuv/domain/party/repository/PartyGroupRepository.java
  src/main/java/com/api/stuv/domain/party/repository/PartyGroupRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/PartyGroupRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/service/PartyService.java
  src/test/java/com/api/stuv/domain/party/repository/PartyGroupRepositoryImplTest.java
Labels: ✨ Feature

#44 [#41] 코스튬 상세조회 기능 구현
  src/main/java/com/api/stuv/domain/admin/service/AdminService.java
  src/main/java/com/api/stuv/domain/shop/controller/CostumeController.java
  src/main/java/com/api/stuv/domain/shop/dto/CostumeResponse.java
  src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryCustom.java
  src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryImpl.java
  src/main/java/com/api/stuv/domain/shop/service/CostumeService.java
Labels: ✨ Feature

#43 [#38] 게시판 작성
  src/main/java/com/api/stuv/domain/board/controller/BoardController.java
  src/main/java/com/api/stuv/domain/board/dto/BoardRequest.java
  src/main/java/com/api/stuv/domain/board/entity/BoardType.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
Labels: ✨ Feature

#45 [#31] 게시판 상세 조회
  src/main/java/com/api/stuv/domain/board/controller/BoardController.java
  src/main/java/com/api/stuv/domain/board/dto/BoardDetailResponse.java
  src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepository.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
Labels: ✨ Feature

#50 [#28] 소셜 로그인 기능 구현
  src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
  src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
  src/main/java/com/api/stuv/domain/auth/service/ReissueService.java
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/dto/request/KakaoUserRequest.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepository.java
  src/main/java/com/api/stuv/domain/user/service/KakaoService.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
  src/main/java/com/api/stuv/global/util/email/RandomCode.java
  src/main/java/com/api/stuv/global/util/email/RandomName.java
  src/main/resources/application.yml
Labels: ✨ Feature

#47 [#46] 답변 채택
  src/main/java/com/api/stuv/domain/board/controller/BoardController.java
  src/main/java/com/api/stuv/domain/board/entity/Board.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
  src/test/java/com/api/stuv/domain/board/service/ConfirmCommentTest.java
Labels: ✨ Feature

#52 [#48] 친구 삭제
  src/main/java/com/api/stuv/domain/board/controller/BoardController.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
Labels: ✨ Feature

#54 [#53] 친구 검색
  src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryCustom.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
Labels: ✨ Feature

#51 [#49] 게시글 이미지 등록 기능 추가 구현
  src/main/java/com/api/stuv/domain/admin/service/AdminService.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/api/stuv/domain/image/entity/EntityType.java
  src/main/java/com/api/stuv/domain/image/entity/ImageFile.java
  src/main/java/com/api/stuv/domain/image/service/ImageService.java
  src/main/java/com/api/stuv/domain/image/service/S3ImageService.java
  src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryImpl.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
Labels: ✨ Feature

#59 [#57] 본인 정보 조회
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/dto/response/MyInformationResponse.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepository.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
Labels: ✨ Feature

#62 [#61] 친구 추천
  src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryCustom.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
Labels: ✨ Feature

#58 [#55] 게시글 삭제
  src/main/java/com/api/stuv/domain/board/controller/BoardController.java
  src/main/java/com/api/stuv/domain/board/repository/CommentRepository.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/image/repository/ImageFileRepository.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
Labels: ✨ Feature

#63 [#56] 게시글 목록조회 이미지 추가 구현
  src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/image/service/ImageService.java
Labels: ✨ Feature

#69 [#65] 게시글 상세조회 이미지 추가 구현
  src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
Labels: ✨ Feature

#71 [#70] 게시글 삭제에서 이미지 삭제 추가 구현
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/image/repository/ImageFileRepository.java
Labels: ✨ Feature

#73 [#72] 코스튬 리팩토링
  src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
  src/main/java/com/api/stuv/domain/admin/service/AdminService.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/api/stuv/domain/image/repository/ImageFileRepository.java
  src/main/java/com/api/stuv/domain/shop/entity/Costume.java
  src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryImpl.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
Labels: ✨ Feature

#78 [#68] 회원 가입 수정
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/dto/request/KakaoUserRequest.java
  src/main/java/com/api/stuv/domain/user/dto/request/UserCostumeRequest.java
  src/main/java/com/api/stuv/domain/user/dto/request/UserRequest.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
Labels: 🔨 Refactor

#76 [#75] 답변 채택 및 삭제 수정
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/user/entity/User.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
  src/test/java/com/api/stuv/domain/board/service/ConfirmCommentTest.java
Labels: 🔨 Refactor

#80 [#74] 게시글 수정
  src/main/java/com/api/stuv/domain/board/controller/BoardController.java
  src/main/java/com/api/stuv/domain/board/dto/BoardUpdateRequest.java
  src/main/java/com/api/stuv/domain/board/entity/Board.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
Labels: ✨ Feature

#88 [#87] 친구 리스폰스 및 리퀘스트 수정
  src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
  src/main/java/com/api/stuv/domain/friend/dto/FriendResponse.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
Labels: 🔨 Refactor, 🐞 BugFix

#82 [#79] 사용자 이미지 정보 조회 추가 구현
  src/main/java/com/api/stuv/domain/image/entity/EntityType.java
  src/main/java/com/api/stuv/domain/user/dto/response/MyInformationResponse.java
  src/main/java/com/api/stuv/domain/user/dto/response/UserInformationResponse.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
Labels: ✨ Feature

#92 [#86] 응답 처리 및 누락 사항 수정
  src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
  src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
Labels: 🔨 Refactor

#93 [#85] todo리스트 추가 기능 구현
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/dto/request/AddTodoRequest.java
  src/main/java/com/api/stuv/domain/user/dto/response/AddTodoResponse.java
  src/main/java/com/api/stuv/domain/user/entity/TodoList.java
  src/main/java/com/api/stuv/domain/user/service/TodoService.java
Labels: ✨ Feature

#95 [#77] 프로필 Url 수정
  src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryImpl.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
Labels: 🔨 Refactor

#89 [#81] 관리자 승인여부가 포함된 전체 팟 목록 조회 기능 구현
  src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
  src/main/java/com/api/stuv/domain/admin/service/AdminService.java
  src/main/java/com/api/stuv/domain/party/dto/response/AdminPartyGroupResponse.java
  src/main/java/com/api/stuv/domain/party/entity/ConfirmStatus.java
  src/main/java/com/api/stuv/domain/party/entity/GroupMember.java
  src/main/java/com/api/stuv/domain/party/entity/PartyGroup.java
  src/main/java/com/api/stuv/domain/party/entity/PartyStatus.java
  src/main/java/com/api/stuv/domain/party/entity/QuestConfirm.java
  src/main/java/com/api/stuv/domain/party/repository/confirm/QuestConfirmRepository.java
  src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepository.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepository.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/service/PartyService.java
  src/test/java/com/api/stuv/domain/admin/service/AdminServiceTest.java
  src/test/java/com/api/stuv/domain/party/repository/PartyGroupRepositoryImplTest.java
Labels: ✨ Feature

#96 [#94] todo리스트 조회 기능 구현
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/dto/response/GetTodoListResponse.java
  src/main/java/com/api/stuv/domain/user/repository/TodoListRepository.java
  src/main/java/com/api/stuv/domain/user/service/TodoService.java
Labels: ✨ Feature

#103 [#90] 팟 인증 상세 조회 기능 구현
  src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
  src/main/java/com/api/stuv/domain/admin/dto/MemberDetailDTO.java
  src/main/java/com/api/stuv/domain/admin/dto/request/CostumeRequest.java
  src/main/java/com/api/stuv/domain/admin/dto/response/AdminPartyAuthDetailResponse.java
  src/main/java/com/api/stuv/domain/admin/dto/response/AdminPartyGroupResponse.java
  src/main/java/com/api/stuv/domain/admin/service/AdminService.java
  src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepository.java
  src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
  src/main/java/com/api/stuv/global/exception/DateOutOfRangeException.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
  src/test/java/com/api/stuv/domain/admin/service/AdminServiceTest.java
Labels: ✨ Feature

#107 [#102] todo 리스트 스케쥴링 및 에러처리
  src/main/java/com/api/stuv/domain/user/service/TodoService.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
  src/main/java/com/api/stuv/global/util/email/TodoListScheduler.java
Labels: ✨ Feature

#112 [#111] 게시글 Response 필드 추가
  src/main/java/com/api/stuv/domain/board/dto/BoardResponse.java
  src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
Labels: 🔨 Refactor

#114 [#83] 게시글 수정 이미지 처리
  src/main/java/com/api/stuv/domain/board/controller/BoardController.java
  src/main/java/com/api/stuv/domain/board/dto/BoardUpdateRequest.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
Labels: ✨ Feature

#116 [#108] 본인 작성글 조회 기능 구현
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/dto/response/UserBoardListResponse.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
Labels: ✨ Feature

#119 [#118] 게시판 및 친구 일부 수정
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepository.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
Labels: 🔨 Refactor

#121 [#91] Dockerfile & cd
  .github/workflows/cd.yml
  Dockerfile
  docker-compose.yml
  src/main/java/com/api/stuv/global/config/S3Config.java
  src/main/resources/application.yml
Labels: 🌏 Deploy

#124 [#123] Socket Error Fix
  src/main/java/com/api/stuv/domain/socket/entity/ChatMessage.java
Labels: 🐞 BugFix

#125 [#122] 에러 사항 수정
  src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
Labels: 🐞 BugFix

#129 [#128] s3 config 수정
  src/main/java/com/api/stuv/global/config/S3Config.java
  src/main/resources/application.yml
Labels: 🌏 Deploy

#131 chron: Board 서비스 수정
  src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryCustom.java
  src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryImpl.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
Labels: 🐞 BugFix

#134 [#127] 개인 퀘스트 보상 받기 기능 구현
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/entity/HistoryType.java
  src/main/java/com/api/stuv/domain/user/entity/PointHistory.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepository.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
Labels: ✨ Feature

#135 [#133] 코스튬 정보 불러오기 수정
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
Labels: 🐞 BugFix

#139 [#138] SecurityConfig CORS 수정
  src/main/java/com/api/stuv/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#142 [#140] 토큰과 사용자 역할에 대한 예외 처리 추가
  src/main/java/com/api/stuv/domain/auth/jwt/JWTFilter.java
  src/main/java/com/api/stuv/domain/auth/util/TokenUtil.java
  src/main/java/com/api/stuv/global/exception/InvalidUserRoleException.java
  src/main/java/com/api/stuv/global/exception/UserNotAuthenticatedException.java
Labels: 🐞 BugFix

#144 [#143] Dockerfile 경로 수정
  Dockerfile
Labels: 🌏 Deploy

#141 [#137] 타이머 조회 기능 구현
  src/main/java/com/api/stuv/domain/timer/controller/TimerController.java
  src/main/java/com/api/stuv/domain/timer/dto/response/TimerListResponse.java
  src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepository.java
  src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepositoryCustom.java
  src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepositoryImpl.java
  src/main/java/com/api/stuv/domain/timer/service/TimerService.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
Labels: ✨ Feature

#148 [#110] 회원의 날짜별 팟 인증에 대한 상태 변경 기능 구현
  src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
  src/main/java/com/api/stuv/domain/admin/dto/request/ConfirmRequest.java
  src/main/java/com/api/stuv/domain/admin/service/AdminService.java
  src/main/java/com/api/stuv/domain/party/entity/GroupMember.java
  src/main/java/com/api/stuv/domain/party/repository/confirm/QuestConfirmRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/confirm/QuestConfirmRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
  src/main/java/com/api/stuv/global/exception/GlobalExceptionHandler.java
  src/main/java/com/api/stuv/global/exception/ValidationException.java
Labels: ✨ Feature

#153 [#147] 타이머 카테고리 삭제 기능 구현
  src/main/java/com/api/stuv/domain/timer/controller/TimerController.java
  src/main/java/com/api/stuv/domain/timer/repository/TimerRepository.java
  src/main/java/com/api/stuv/domain/timer/service/TimerService.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
Labels: ✨ Feature

#156 [#155] 코스튬 조회 기능 구현
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/dto/response/GetCostume.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
Labels: ✨ Feature

#160 [#126] 채팅 메시지 응답 구조 개선 및 날짜 포맷 적용
  src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
  src/main/java/com/api/stuv/domain/socket/controller/ChatMessageController.java
  src/main/java/com/api/stuv/domain/socket/dto/ChatMessageResponse.java
  src/main/java/com/api/stuv/domain/socket/dto/ReadByResponse.java
  src/main/java/com/api/stuv/domain/socket/entity/ChatMessage.java
  src/main/java/com/api/stuv/domain/socket/service/ChatMessageService.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomMemberService.java
Labels: 🔨 Refactor

#164 [#161] 카카오 로그인 기능 수정
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/service/KakaoService.java
  src/main/resources/application.yml
Labels: 🔨 Refactor

#168 [#167] cors 관련 핫픽스
  src/main/java/com/api/stuv/global/config/SecurityConfig.java
Labels: 🐞 BugFix

#163 [#154] 자신의 공부 시간 저장 기능 구현 With Redis
  src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryImpl.java
  src/main/java/com/api/stuv/domain/timer/controller/TimerController.java
  src/main/java/com/api/stuv/domain/timer/dto/request/StudyTimeRequest.java
  src/main/java/com/api/stuv/domain/timer/dto/response/TimerListResponse.java
  src/main/java/com/api/stuv/domain/timer/entity/StudyTime.java
  src/main/java/com/api/stuv/domain/timer/entity/StudyTimeId.java
  src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepository.java
  src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepositoryCustom.java
  src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepositoryImpl.java
  src/main/java/com/api/stuv/domain/timer/repository/TimerRepository.java
  src/main/java/com/api/stuv/domain/timer/service/TimerService.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
  src/main/java/com/api/stuv/global/service/RedisService.java
  src/main/java/com/api/stuv/global/util/common/TemplateUtils.java
  src/main/java/com/api/stuv/global/util/scheduler/TimerScheduler.java
  src/main/java/com/api/stuv/global/util/scheduler/TodoListScheduler.java
Labels: ✨ Feature

#171 [#166] user 정보 반환 변경
  src/main/java/com/api/stuv/domain/user/dto/response/MyInformationResponse.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
  src/main/resources/application.yml
Labels: 🔨 Refactor

#172 [#132] cd 버전 변경
  .github/workflows/cd.yml
Labels: 🌏 Deploy

#173 [#157] 코스튬 변경 기능 구현
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/dto/response/ChangeUserCostume.java
  src/main/java/com/api/stuv/domain/user/entity/User.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
Labels: ✨ Feature

#175 [#174] 쿠키 설정 핫픽스
  src/main/java/com/api/stuv/domain/auth/controller/ReissueController.java
  src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
  src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
  src/main/java/com/api/stuv/domain/user/service/KakaoService.java
Labels: 🐞 BugFix

#181 [hotfix] cookie 설정 변경
  src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
  src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
  src/main/java/com/api/stuv/domain/user/service/KakaoService.java
  src/main/java/com/api/stuv/global/config/SecurityConfig.java
Labels: 🐞 BugFix

#183 [hotfix] cookie 설정 변경
  src/main/java/com/api/stuv/domain/auth/controller/ReissueController.java
  src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
  src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
  src/main/java/com/api/stuv/domain/user/service/KakaoService.java
  src/main/java/com/api/stuv/global/config/SecurityConfig.java
Labels: 🐞 BugFix

#184 [hotfix] cookie 설정 변경
  src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
Labels: 🐞 BugFix

#186 [#185] cd 파일 수정
  .github/workflows/cd.yml
Labels: 🐞 BugFix, 🌏 Deploy

#187 [#185] 배포 파일 수정
  .github/workflows/cd.yml
Labels: 🌏 Deploy
