Repository prgrms-web-devcourse-final-project/WEB2_3_Wooamo_BE, pull requests merged in 2025-03, with the labels that each got.

#192 [fix] 프론트 요청사항 핫픽스
  src/main/java/com/api/stuv/domain/board/dto/BoardDetailResponse.java
  src/main/java/com/api/stuv/domain/timer/controller/TimerController.java
  src/main/java/com/api/stuv/domain/timer/dto/request/AddTimerCategoryRequest.java
  src/main/java/com/api/stuv/domain/timer/dto/response/AddTimerCategoryResponse.java
  src/main/java/com/api/stuv/domain/timer/dto/response/AddTimerCatetoryResponse.java
  src/main/java/com/api/stuv/domain/timer/service/TimerService.java
  src/main/java/com/api/stuv/domain/user/dto/response/UserBoardListResponse.java
  src/main/java/com/api/stuv/global/response/PageResponse.java
Labels: 🐞 BugFix

#193 [fix] 코멘트 추가 API 요청에 대한 항목 수정
  src/main/java/com/api/stuv/domain/board/controller/BoardController.java
  src/main/java/com/api/stuv/domain/board/dto/CommentRequest.java
Labels: 🐞 BugFix

#195 fix: docker compose 수정
  .github/workflows/cd.yml
Labels: 🐞 BugFix, 🌏 Deploy

#197 [#191] cookie 설정 변경
  src/main/java/com/api/stuv/domain/auth/controller/ReissueController.java
  src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
  src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
  src/main/java/com/api/stuv/domain/user/service/KakaoService.java
Labels: 🐞 BugFix

#198 [hotfix] cookie 설정 변경
  src/main/java/com/api/stuv/domain/auth/controller/ReissueController.java
  src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
  src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
  src/main/java/com/api/stuv/domain/user/service/KakaoService.java
Labels: 🐞 BugFix

#196 [#190] 코스튬 구매 기능 구현
  src/main/java/com/api/stuv/domain/shop/controller/ShopController.java
  src/main/java/com/api/stuv/domain/shop/dto/CostumePurchaseRequest.java
  src/main/java/com/api/stuv/domain/shop/exception/CostumeAlreadyException.java
  src/main/java/com/api/stuv/domain/shop/exception/PointNotEnoughException.java
  src/main/java/com/api/stuv/domain/shop/service/CostumeService.java
  src/main/java/com/api/stuv/domain/user/entity/User.java
  src/main/java/com/api/stuv/domain/user/repository/UserCostumeRepository.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepository.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
Labels: ✨ Feature

#203 [#200] 코스튬 랜덤 구매
  src/main/java/com/api/stuv/domain/shop/controller/ShopController.java
  src/main/java/com/api/stuv/domain/shop/dto/CostumeRandomRequest.java
  src/main/java/com/api/stuv/domain/shop/dto/CostumeRandomResponse.java
  src/main/java/com/api/stuv/domain/shop/exception/CostumeNotPurchaseException.java
  src/main/java/com/api/stuv/domain/shop/service/CostumeService.java
  src/main/java/com/api/stuv/domain/user/entity/User.java
  src/main/java/com/api/stuv/domain/user/repository/UserCostumeRepository.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
Labels: ✨ Feature

#204 [hotfix] cookie 설정 변경
  src/main/java/com/api/stuv/domain/auth/controller/ReissueController.java
  src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
  src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
  src/main/java/com/api/stuv/domain/user/service/KakaoService.java
Labels: 🐞 BugFix

#201 [#165] 회원의 기간 단위별 공부시간 조회
  src/main/java/com/api/stuv/domain/timer/controller/TimerController.java
  src/main/java/com/api/stuv/domain/timer/dto/response/StudyDateTimeResponse.java
  src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepository.java
  src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepositoryCustom.java
  src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepositoryImpl.java
  src/main/java/com/api/stuv/domain/timer/service/TimerService.java
  src/main/java/com/api/stuv/domain/timer/util/TimerUtil.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
  src/main/java/com/api/stuv/global/exception/GlobalExceptionHandler.java
Labels: ✨ Feature

#205 [hotfix] cookie 설정 핫픽스
  src/main/java/com/api/stuv/domain/auth/controller/ReissueController.java
  src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
  src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
  src/main/java/com/api/stuv/domain/user/service/KakaoService.java
Labels: 🐞 BugFix

#209 [#208] 코스튬 변경 기능 수정
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
Labels: 🐞 BugFix

#210 [#162] 채팅방 목록 및 페이징 응답 수정
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
  src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
  src/main/java/com/api/stuv/domain/socket/controller/ChatMessageController.java
  src/main/java/com/api/stuv/domain/socket/dto/ChatMessageResponse.java
  src/main/java/com/api/stuv/domain/socket/dto/ChatRoomResponse.java
  src/main/java/com/api/stuv/domain/socket/dto/ReadByResponse.java
  src/main/java/com/api/stuv/domain/socket/entity/ChatRoom.java
  src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepository.java
  src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepositoryCustom.java
  src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepositoryImpl.java
  src/main/java/com/api/stuv/domain/socket/repository/ChatRoomRepository.java
  src/main/java/com/api/stuv/domain/socket/service/ChatMessageService.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
Labels: 🔨 Refactor

#211 [#202] 주간 공부시간 랭킹 구현
  src/main/java/com/api/stuv/domain/timer/dto/UserRankDTO.java
  src/main/java/com/api/stuv/domain/timer/dto/response/RankInfoResponse.java
  src/main/java/com/api/stuv/domain/timer/dto/response/RankResponse.java
  src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepositoryCustom.java
  src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepositoryImpl.java
  src/main/java/com/api/stuv/domain/timer/service/TimerService.java
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/dto/UserProfileInfoDTO.java
  src/main/java/com/api/stuv/domain/user/entity/HistoryType.java
  src/main/java/com/api/stuv/domain/user/entity/RewardType.java
  src/main/java/com/api/stuv/domain/user/entity/User.java
  src/main/java/com/api/stuv/domain/user/repository/PointHistoryRepository.java
  src/main/java/com/api/stuv/domain/user/repository/PointHistoryRepositoryCustom.java
  src/main/java/com/api/stuv/domain/user/repository/PointHistoryRepositoryImpl.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/api/stuv/global/util/initializer/ApplicationInitializer.java
  src/main/java/com/api/stuv/global/util/scheduler/TimerScheduler.java
  src/main/java/com/api/stuv/global/util/scheduler/TodoListScheduler.java
Labels: ✨ Feature

#214 [#213] Board 서비스 수정
  src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
Labels: 🐞 BugFix

#217 [#216] docker-compose time zone 수정
  docker-compose.yml
Labels: 🌏 Deploy

#219 [#218] todo isChecked 디폴트값 설정
  src/main/java/com/api/stuv/domain/user/entity/TodoList.java
Labels: 🐞 BugFix

#220 [#215] 일일 총 공부시간 -> 마리아디비에서 레디스로 조회방식 변경
  src/main/java/com/api/stuv/domain/timer/dto/response/RankInfoResponse.java
  src/main/java/com/api/stuv/domain/timer/service/TimerService.java
Labels: 🔨 Refactor

#223 [#212] 개인방 및 그룹방 채팅 생성, 업데이트, 삭제
  src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
  src/main/java/com/api/stuv/domain/socket/entity/ChatRoom.java
  src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepository.java
  src/main/java/com/api/stuv/domain/socket/repository/ChatRoomRepository.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
Labels: ✨ Feature

#225 [#224] profile 없는 경우 null 출력
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
Labels: 🐞 BugFix

#227 [#226] 포인트 내역 저장
  src/main/java/com/api/stuv/domain/shop/service/CostumeService.java
  src/main/java/com/api/stuv/domain/shop/service/PaymentService.java
Labels: ✨ Feature

#228 [#152] 마감된 팟 목록 조회 (보상 획득 여부, 포인트, 성공여부)
  src/main/java/com/api/stuv/domain/party/controller/PartyController.java
  src/main/java/com/api/stuv/domain/party/dto/MemberRewardStatusDTO.java
  src/main/java/com/api/stuv/domain/party/dto/response/PartyRewardStatusResponse.java
  src/main/java/com/api/stuv/domain/party/entity/QuestStatus.java
  src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/service/PartyService.java
Labels: ✨ Feature

#231 [#229] 팟 상세 정보 조회 (자신의 참가여부 포함) 기능
  src/main/java/com/api/stuv/domain/party/controller/PartyController.java
  src/main/java/com/api/stuv/domain/party/dto/response/PartyDetailResponse.java
  src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/service/PartyService.java
Labels: ✨ Feature

#235 [#233] 소셜로그인 응답 주소 변경
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/service/KakaoService.java
Labels: 🐞 BugFix

#234 [#230] 응답 수정 및 에러 코드 수정
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
  src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
  src/main/java/com/api/stuv/domain/socket/dto/AddUserToGroupChatRequest.java
  src/main/java/com/api/stuv/domain/socket/dto/ChatRoomResponse.java
  src/main/java/com/api/stuv/domain/socket/dto/CreateGroupRoomRequest.java
  src/main/java/com/api/stuv/domain/socket/dto/CreatePrivateRoomRequest.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
Labels: 🐞 BugFix

#237 [#236] 구매 후 코스튬 이름 반환
  src/main/java/com/api/stuv/domain/shop/service/CostumeService.java
Labels: 🐞 BugFix

#240 [#66] 알림 기능 기초적으로 완성
  src/main/java/com/api/stuv/domain/alert/controller/AlertController.java
  src/main/java/com/api/stuv/domain/alert/controller/SseController.java
  src/main/java/com/api/stuv/domain/alert/dto/AlertResponse.java
  src/main/java/com/api/stuv/domain/alert/entity/Alert.java
  src/main/java/com/api/stuv/domain/alert/entity/AlertType.java
  src/main/java/com/api/stuv/domain/alert/repository/AlertRedisRepository.java
  src/main/java/com/api/stuv/domain/alert/service/AlertService.java
  src/main/java/com/api/stuv/domain/alert/service/SseService.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
  src/main/java/com/api/stuv/global/config/RedisConfig.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
  src/main/java/com/api/stuv/global/exception/GlobalExceptionHandler.java
  src/main/java/com/api/stuv/global/exception/JsonParseException.java
  src/main/java/com/api/stuv/global/exception/SseErrorException.java
  src/main/java/com/api/stuv/global/service/RedisPublisher.java
  src/main/java/com/api/stuv/global/service/RedisService.java
  src/main/java/com/api/stuv/global/service/RedisSubscriber.java
  src/main/java/com/api/stuv/global/util/common/TemplateUtils.java
  src/test/java/com/api/stuv/domain/board/service/ConfirmCommentTest.java
Labels: ✨ Feature

#239 [#238] 버그 사항 수정
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryCustom.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/api/stuv/domain/user/dto/response/MyInformationResponse.java
  src/main/java/com/api/stuv/domain/user/dto/response/UserInformationResponse.java
  src/main/java/com/api/stuv/domain/user/repository/UserCostumeRepository.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
Labels: 🐞 BugFix

#242 [#232] 팟 생성 및 참가 기능 구현
  src/main/java/com/api/stuv/domain/party/controller/PartyController.java
  src/main/java/com/api/stuv/domain/party/dto/request/PartyCreateRequest.java
  src/main/java/com/api/stuv/domain/party/dto/request/PartyJoinRequest.java
  src/main/java/com/api/stuv/domain/party/dto/response/PartyIdResponse.java
  src/main/java/com/api/stuv/domain/party/entity/GroupMember.java
  src/main/java/com/api/stuv/domain/party/entity/PartyGroup.java
  src/main/java/com/api/stuv/domain/party/service/PartyService.java
  src/main/java/com/api/stuv/domain/timer/service/TimerService.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
Labels: ✨ Feature

#245 [#244] API 버그 및 이슈 수정
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/dto/response/UserInformationResponse.java
  src/main/java/com/api/stuv/domain/user/repository/UserCostumeRepository.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
Labels: 🐞 BugFix

#246 [#241] 유저 검색 수정
  src/main/java/com/api/stuv/domain/friend/dto/FriendResponse.java
  src/main/java/com/api/stuv/domain/friend/entity/FriendFollowStatus.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
Labels: 🔨 Refactor

#247 [#243] 팟 참여자 목록 조회 및 이벤트 배너 조회 기능 구현
  src/main/java/com/api/stuv/domain/party/controller/PartyController.java
  src/main/java/com/api/stuv/domain/party/dto/MemberDTO.java
  src/main/java/com/api/stuv/domain/party/dto/response/EventBannerResponse.java
  src/main/java/com/api/stuv/domain/party/dto/response/MemberResponse.java
  src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/service/PartyService.java
  src/main/java/com/api/stuv/domain/timer/controller/TimerController.java
  src/main/java/com/api/stuv/domain/timer/service/TimerService.java
  src/main/java/com/api/stuv/domain/user/entity/UserStatus.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
  src/main/java/com/api/stuv/global/exception/GlobalExceptionHandler.java
Labels: ✨ Feature

#254 [#253] Alert Response 수정
  src/main/java/com/api/stuv/domain/alert/dto/AlertResponse.java
  src/main/java/com/api/stuv/domain/alert/entity/Alert.java
  src/main/java/com/api/stuv/domain/alert/service/AlertService.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
Labels: 🔨 Refactor

#255 [#248] 팟 인증 및 보상 획득 기능 구현
  src/main/java/com/api/stuv/domain/party/controller/PartyController.java
  src/main/java/com/api/stuv/domain/party/dto/response/PartyDetailResponse.java
  src/main/java/com/api/stuv/domain/party/dto/response/PointResponse.java
  src/main/java/com/api/stuv/domain/party/repository/confirm/QuestConfirmRepository.java
  src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/service/PartyService.java
  src/main/java/com/api/stuv/domain/user/entity/User.java
  src/main/java/com/api/stuv/domain/user/repository/PointHistoryRepository.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
  src/main/java/com/api/stuv/global/util/scheduler/TimerScheduler.java
Labels: ✨ Feature

#257 [#249] 코스튬 s3 리팩토링
  src/main/java/com/api/stuv/domain/shop/controller/ShopController.java
  src/main/java/com/api/stuv/domain/shop/dto/costume/CostumeDTO.java
  src/main/java/com/api/stuv/domain/shop/dto/costume/CostumePurchaseRequest.java
  src/main/java/com/api/stuv/domain/shop/dto/costume/CostumeRandomRequest.java
  src/main/java/com/api/stuv/domain/shop/dto/costume/CostumeRandomResponse.java
  src/main/java/com/api/stuv/domain/shop/dto/costume/CostumeResponse.java
  src/main/java/com/api/stuv/domain/shop/dto/payments/PaymentConfirmRequest.java
  src/main/java/com/api/stuv/domain/shop/dto/payments/PaymentRequest.java
  src/main/java/com/api/stuv/domain/shop/dto/payments/PaymentResponse.java
  src/main/java/com/api/stuv/domain/shop/dto/payments/TossPaymentRequest.java
  src/main/java/com/api/stuv/domain/shop/dto/payments/TossPaymentResponse.java
  src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryCustom.java
  src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryImpl.java
  src/main/java/com/api/stuv/domain/shop/service/CostumeService.java
  src/main/java/com/api/stuv/domain/shop/service/PaymentService.java
Labels: 🔨 Refactor

#259 [#256] 관리자 주간 정보 조회 및 최근 매출 내역 조회
  src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
  src/main/java/com/api/stuv/domain/admin/dto/response/PointSalesResponse.java
  src/main/java/com/api/stuv/domain/admin/dto/response/WeeklyInfoResponse.java
  src/main/java/com/api/stuv/domain/admin/service/AdminService.java
  src/main/java/com/api/stuv/domain/image/dto/ImageDTO.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
  src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryCustom.java
  src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryImpl.java
  src/main/java/com/api/stuv/domain/shop/repository/PaymentRepository.java
  src/main/java/com/api/stuv/domain/shop/repository/PaymentRepositoryCustom.java
  src/main/java/com/api/stuv/domain/shop/repository/PaymentRepositoryImpl.java
  src/main/java/com/api/stuv/domain/user/repository/PointHistoryRepositoryCustom.java
  src/main/java/com/api/stuv/domain/user/repository/PointHistoryRepositoryImpl.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
Labels: 🐞 BugFix, ✨ Feature

#261 [#251] user refactoring
  src/main/java/com/api/stuv/domain/auth/service/ReissueService.java
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/global/service/RedisService.java
  src/main/resources/application.yml
Labels: 🔨 Refactor, 🐞 BugFix

#265 [#260] 관리자 이벤트 팟 등록 및 조회하기
  src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
  src/main/java/com/api/stuv/domain/admin/dto/request/EventPartyRequest.java
  src/main/java/com/api/stuv/domain/admin/dto/response/EventPartyResponse.java
  src/main/java/com/api/stuv/domain/admin/service/AdminService.java
  src/main/java/com/api/stuv/domain/party/entity/PartyGroup.java
  src/main/java/com/api/stuv/domain/party/repository/confirm/QuestConfirmRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/service/PartyService.java
  src/test/java/com/api/stuv/domain/admin/service/AdminServiceTest.java
Labels: ✨ Feature

#266 [#250] 게시글 및 친구 리펙터링
  src/main/java/com/api/stuv/domain/board/controller/BoardController.java
  src/main/java/com/api/stuv/domain/board/dto/BoardResponse.java
  src/main/java/com/api/stuv/domain/board/dto/dto/BoardDetailDTO.java
  src/main/java/com/api/stuv/domain/board/dto/dto/BoardListDTO.java
  src/main/java/com/api/stuv/domain/board/dto/dto/CommentDTO.java
  src/main/java/com/api/stuv/domain/board/dto/request/BoardRequest.java
  src/main/java/com/api/stuv/domain/board/dto/request/BoardUpdateRequest.java
  src/main/java/com/api/stuv/domain/board/dto/request/CommentRequest.java
  src/main/java/com/api/stuv/domain/board/dto/response/BoardDetailResponse.java
  src/main/java/com/api/stuv/domain/board/dto/response/BoardIdResponse.java
  src/main/java/com/api/stuv/domain/board/dto/response/BoardResponse.java
  src/main/java/com/api/stuv/domain/board/dto/response/CommentResponse.java
  src/main/java/com/api/stuv/domain/board/entity/Board.java
  src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryCustom.java
  src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryImpl.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
  src/main/java/com/api/stuv/domain/friend/dto/FriendFollowListResponse.java
  src/main/java/com/api/stuv/domain/friend/dto/dto/FriendListDTO.java
  src/main/java/com/api/stuv/domain/friend/dto/dto/FriendRecommendDTO.java
  src/main/java/com/api/stuv/domain/friend/dto/response/FriendFollowResponse.java
  src/main/java/com/api/stuv/domain/friend/dto/response/FriendResponse.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryCustom.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
  src/main/java/com/api/stuv/global/response/PageResponse.java
  src/test/java/com/api/stuv/domain/friend/service/AcceptFriendRequestTest.java
Labels: 🔨 Refactor

#273 [#268] 게시글 상세 조회 이미지 변경
  src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
Labels: 🔨 Refactor

#269 [#258] user s3service 리팩토링
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomMemberService.java
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/dto/ImageUrlDTO.java
  src/main/java/com/api/stuv/domain/user/dto/MyInformationDTO.java
  src/main/java/com/api/stuv/domain/user/dto/UserBoardListDTO.java
  src/main/java/com/api/stuv/domain/user/dto/UserInformationDTO.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
Labels: 🔨 Refactor

#279 [#278] 코스튬 삭제 트랜잭션 추가
  src/main/java/com/api/stuv/domain/admin/service/AdminService.java
Labels: 🐞 BugFix

#280 [#277] 로그인 응답 수정
  src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
  src/main/java/com/api/stuv/domain/auth/service/CustomUserDetailsService.java
  src/main/java/com/api/stuv/domain/user/dto/response/LoginResponse.java
Labels: 🔨 Refactor

#283 [#281] 카카오 로그인 응답 및 내 정보 조회 에러 수정
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/service/KakaoService.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
Labels: 🐞 BugFix

#282 [#276] 유저 검색 응답 수정
  src/main/java/com/api/stuv/domain/friend/entity/FriendFollowStatus.java
  src/main/java/com/api/stuv/domain/friend/entity/FriendStatus.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
Labels: 🔨 Refactor

#286 [#285] 관리자 팟 목록 및 인증 승인 화면 핫픽스
  src/main/java/com/api/stuv/domain/admin/service/AdminService.java
  src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
Labels: 🔨 Refactor, 🐞 BugFix

#287 [#284] reissue status 코드 변경 및 이미지 출력 수정
  src/main/java/com/api/stuv/domain/auth/service/ReissueService.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
Labels: 🐞 BugFix

#290 [#289] 친구 검색 픽스
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
Labels: 🐞 BugFix

#293 [#292] 목록 조회 정렬
  src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
Labels: 🐞 BugFix

#295 [#294] SecurityConfig 수정
  src/main/java/com/api/stuv/global/config/SecurityConfig.java
Labels: 🐞 BugFix

#296 [#291] 채팅방 멤버 정보 전송 및 응답 수정
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
  src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
  src/main/java/com/api/stuv/domain/socket/dto/ChatRoomInfoResponse.java
  src/main/java/com/api/stuv/domain/socket/dto/ChatRoomResponse.java
  src/main/java/com/api/stuv/domain/socket/dto/GroupInfo.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomMemberService.java
Labels: 🐞 BugFix

#298 [#297] kakao redirect uri 변경
  src/main/java/com/api/stuv/domain/user/service/KakaoService.java
Labels: 💻 CrossBrowsing

#302 [#300] 그룹 채팅방 응답 수정
  src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
  src/main/java/com/api/stuv/domain/socket/dto/ChatRoomInfoResponse.java
  src/main/java/com/api/stuv/domain/socket/dto/ChatRoomResponse.java
  src/main/java/com/api/stuv/domain/socket/dto/CreateGroupRoomRequest.java
  src/main/java/com/api/stuv/domain/socket/dto/GroupInfo.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
Labels: 🐞 BugFix

#304 [#299] 읽음 처리 관련 방 세션 관리 수정
  src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
  src/main/java/com/api/stuv/domain/socket/controller/ChatMessageController.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomMemberService.java
Labels: 🐞 BugFix

#305 [#303] 팟 및 관리자 기능 핫픽스, 일부 출력문 제거
  src/main/java/com/api/stuv/domain/alert/service/AlertService.java
  src/main/java/com/api/stuv/domain/party/dto/response/PartyDetailResponse.java
  src/main/java/com/api/stuv/domain/party/repository/confirm/QuestConfirmRepository.java
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
  src/main/java/com/api/stuv/domain/party/service/PartyService.java
  src/main/java/com/api/stuv/domain/shop/repository/PaymentRepositoryImpl.java
  src/main/java/com/api/stuv/domain/timer/service/TimerService.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
Labels: 🐞 BugFix

#311 [#308]: 채팅방 1:1방, 그룹방 정보 응답 오류 수정
  src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
  src/main/java/com/api/stuv/domain/socket/controller/ChatMessageController.java
  src/main/java/com/api/stuv/domain/socket/dto/ChatRoomTypeInfoResponse.java
  src/main/java/com/api/stuv/domain/socket/dto/UserInfoWithContext.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
Labels: 🐞 BugFix

#310 [#309] docker 정리
  .github/workflows/cd.yml
Labels: 🐞 BugFix, 🌏 Deploy

#314 [#313] 코멘트 순서 수정
  src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryImpl.java
Labels: 🐞 BugFix

#318 [#106] 옵저버빌리티 적용 전 기반 설정 적용 및 카프카 관련 설정 삭제
  .github/workflows/ci.yml
  build.gradle
  docker-compose.yml
  src/main/java/com/api/stuv/global/config/KafkaConfig.java
  src/main/resources/application.yml
Labels: ⚙ Setting

#319 [#316] 메세지 불러오기 페이지네이션 수정
  src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
  src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepositoryCustom.java
  src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepositoryImpl.java
  src/main/java/com/api/stuv/domain/socket/service/ChatMessageService.java
Labels: 🐞 BugFix

#320 [#317] Alert 기능 일부 수정
  src/main/java/com/api/stuv/domain/alert/dto/AlertEventDTO.java
  src/main/java/com/api/stuv/domain/alert/dto/AlertExpireDTO.java
  src/main/java/com/api/stuv/domain/alert/entity/Alert.java
  src/main/java/com/api/stuv/domain/alert/service/AlertService.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
  src/main/java/com/api/stuv/global/service/RedisService.java
  src/main/java/com/api/stuv/global/util/common/TemplateUtils.java
  src/test/java/com/api/stuv/domain/board/service/ConfirmCommentTest.java
Labels: 🔨 Refactor

#324 [#321] 로그인 여부 확인 기능 구현 및 회원 정보 수정
  src/main/java/com/api/stuv/domain/user/controller/UserController.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
Labels: ✨ Feature

#327 [#326] 친구 목록 조회 수정
  src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
Labels: 🔨 Refactor, 🐞 BugFix

#331 [#328] logout 에러 수정
  src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
Labels: 🐞 BugFix

#333 [#332] party 예외 추가 및 금액 차감 핫픽스
  src/main/java/com/api/stuv/domain/admin/service/AdminService.java
  src/main/java/com/api/stuv/domain/party/service/PartyService.java
  src/main/java/com/api/stuv/global/exception/ErrorCode.java
Labels: 🐞 BugFix

#335 [#334] 친구 아닌 회원 검색 수정
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
Labels: 🐞 BugFix

#339 [#336] sse 수정
  src/main/java/com/api/stuv/domain/alert/service/SseService.java
Labels: 🐞 BugFix

#338 [#337] 메세지 응답 오류 수정수정
  src/main/java/com/api/stuv/domain/socket/dto/ChatMessageResponse.java
  src/main/java/com/api/stuv/domain/socket/service/ChatMessageService.java
Labels: 🐞 BugFix

#341 [#340] 읽음 상태 업데이트 소켓 통신 변경
  src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
  src/main/java/com/api/stuv/domain/socket/controller/ChatMessageController.java
  src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepositoryCustom.java
  src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepositoryImpl.java
  src/main/java/com/api/stuv/domain/socket/service/ChatMessageService.java
Labels: 🔨 Refactor

#343 [#342] Observability 설정
  .gitignore
  build.gradle
  docker-compose.yml
  docker/grafana/config/grafana.ini
  docker/loki/config/local-config.yaml
  docker/prometheus/config/prometheus.yml
  docker/tempo/config/tempo.yaml
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: ✨ Feature, 🌏 Deploy

#344 [#322] 읽음 상태 업데이트 소켓 통신 변경
  src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
  src/main/java/com/api/stuv/domain/socket/controller/ChatMessageController.java
  src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepositoryImpl.java
  src/main/java/com/api/stuv/domain/socket/service/ChatMessageService.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomMemberService.java
  src/main/java/com/api/stuv/global/config/RedisConfig.java
Labels: 🔨 Refactor

#346 [#345] 도커 권한 관련 에러 핫픽스
  docker-compose.yml
Labels: 🐞 BugFix

#348 [#347] 코스튬 변경 시 채팅방 프로필 변경
  src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
  src/main/java/com/api/stuv/domain/socket/controller/ChatMessageController.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomMemberService.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
Labels: 🐞 BugFix

#351 [#349] 게시판 및 친구 일부 기능 페이지네이션 제거
  src/main/java/com/api/stuv/domain/board/controller/BoardController.java
  src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryCustom.java
  src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryImpl.java
  src/main/java/com/api/stuv/domain/board/service/BoardService.java
  src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryCustom.java
  src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/com/api/stuv/domain/friend/service/FriendService.java
Labels: 🔨 Refactor

#352 [#350] 참여중인 팟 목록에서 인원수가 잘못 나오는 버그 수정
  src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#355 [#354] 채팅방 메시지 범위 조회 응답 예외 처리
  src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
  src/main/java/com/api/stuv/domain/socket/service/ChatMessageService.java
Labels: 🐞 BugFix

#357 [#353] 로그인 access토큰 블랙리스트 설정
  src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
  src/main/java/com/api/stuv/domain/auth/jwt/JWTFilter.java
  src/main/java/com/api/stuv/domain/auth/jwt/JWTUtil.java
  src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
  src/main/java/com/api/stuv/domain/auth/service/ReissueService.java
  src/main/java/com/api/stuv/domain/user/service/KakaoService.java
  src/main/java/com/api/stuv/global/config/SecurityConfig.java
Labels: ✨ Feature

#359 [#358] 알림 삭제 수정
  src/main/java/com/api/stuv/global/service/RedisService.java
Labels: 🐞 BugFix

#361 [#360] 이메일 확인 코드 템플릿 디자인
  src/main/java/com/api/stuv/global/util/email/provider/EmailProvider.java
  src/main/resources/application.yml
  src/main/resources/static/STUV.png
  src/main/resources/templates/email-template.html
Labels: 🎨 Html&css, ✨ Feature

#362 [#323] 무중단 배포
  .github/workflows/cd.yml
  deploy.sh
  docker-compose.yml
  docker/Dockerfile
  docker/proxy/conf.d/default.conf.template
  docker/proxy/nginx.conf
Labels: 🌏 Deploy

#364 fix: 컨테이너 상태 확인 수정
  deploy.sh
Labels: 🐞 BugFix

#366 [#323] nginx 사용자 변경
  docker/proxy/nginx.conf
Labels: 🐞 BugFix, 🌏 Deploy

#368 [#323] nginx 내부 명령어 변경
  deploy.sh
Labels: 🐞 BugFix, 🌏 Deploy

#369 [#fix] 블루그린 배포에 맞춰 수집기 설정 변경
  docker/prometheus/config/prometheus.yml
Labels: 🐞 BugFix

#370 [#fix] 옵저버빌리티 ec2 내부 데이터 저장 디렉토리 변경
  docker-compose.yml
Labels: 🐞 BugFix

#373 [#372] 코스튬 목록 조회 리팩토링
  src/main/java/com/api/stuv/domain/shop/controller/ShopController.java
  src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryCustom.java
  src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryImpl.java
  src/main/java/com/api/stuv/domain/shop/service/CostumeService.java
Labels: 🔨 Refactor

#375 [#hotfix] 파일 용량 제한 변경
  src/main/resources/application.yml
Labels: 🥰 Accessibility

#376 [#374] 배포 서버 실행 대기
  deploy.sh
Labels: 🐞 BugFix, 🌏 Deploy

#377 [#374] 배포 서버 실행 시간 수정
  deploy.sh
Labels: 🐞 BugFix, 🌏 Deploy

#379 [#356] 채팅 서비스 역할 분리 및 중복 코드 제거 및 구조 개선
  src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
  src/main/java/com/api/stuv/domain/socket/controller/ChatMessageController.java
  src/main/java/com/api/stuv/domain/socket/service/ChatMessageSenderService.java
  src/main/java/com/api/stuv/domain/socket/service/ChatMessageService.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomMemberService.java
  src/main/java/com/api/stuv/domain/socket/service/ChatRoomStatusService.java
Labels: 🔨 Refactor

#380 [#374] 사용하지 않는 docker 정리
  deploy.sh
Labels: 🐞 BugFix, 🌏 Deploy

#382 [#381] Update README.md
  README.md
Labels: 📃 Docs

#390 [#389] 일반 회원가입 소셜 회원가입 연결
  src/main/java/com/api/stuv/domain/user/entity/User.java
  src/main/java/com/api/stuv/domain/user/service/UserService.java
Labels: ✨ Feature

#394 [#393] 이미지 확장자 추가
  src/main/java/com/api/stuv/domain/image/service/ImageService.java
Labels: 🔨 Refactor
